### ISSUE TITLE
Add support for JSON,YAML,XML

### ISSUE THREAD

**Issue by tismatis** [tismatis/AutoBackupFiles#6]
Could be great if you don't want keep using an csv file. For example:
Here in CSV:
```csv
config;force-zip;true
folder;My Documents;C:\Users\tismatis\Documents
ignore-folder;My Documents;C:\Users\tismatis\Documents\Nextcloud
```
Here in JSON:
```json
{
    "configuration":
    {
        "force-zip": true
    },
    "backups":
    {
        "My Documents":
        {
            "Folders":
            [
                "C:\\Users\\tismatis\\Documents"
            ],
            "Ignore":
            [
                "C:\\Users\\tismatis\\Documents\\Nextcloud"
            ]
        }
    }
}
```
Here in YAML:
```yaml
---
configuration:
  force-zip: true
backups:
  My Documents:
    Folders:
    - C:\Users\tismatis\Documents
    Ignore:
    - C:\Users\tismatis\Documents\Nextcloud
```
And finally here in XML:
```xml
<?xml version="1.0" encoding="UTF-8" ?>
 <root>
     <configuration>
         <force-zip>true</force-zip>
     </configuration>
     <backup name="My Documents">
         <Folder>C:\Users\tismatis\Documents</Folder>
         <Ignore>C:\Users\tismatis\Documents\Nextcloud</Ignore>
     </backup>
 </root>
```
Btw, these are examples, Idk if that will be implemented exactly like this after.
